<?php
// $Id: username.install

/**
* Implementation of hook_install()
*/
function username_install() {
  // Set the module weight so it can override other modules.
  db_query("UPDATE {system} SET weight = 99 WHERE name = 'username'");
}

/**
* Implementation of hook_uninstall()
*/
function username_uninstall() {
  // Remove the module from the system table
  db_query("DELETE FROM {system} WHERE name = 'username'");
}