<?php
// $Id: customsite.module

/**
* @file
* Custom functions for this site.
*/




//HOOK_HELP

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/

ctools_include('dependent');

function customsite_help($path, $arg) {
 $output = '';  //declare your output variable
  switch ($path) {
    case 'admin/help#customsite':
      $output = '<p>'.  t("Sample help text") .'</p>';
      break;
  }
  return $output;
} // function customsite_help




//HOOK_PERM

/**
* Valid permissions for this module
* @return array An array of valid permissions for the customsite module
*/
function customsite_perm() {
  return array('access customsite content');
} // function customsite_perm()





//HOOK_BLOCK

/**
* Implementation of hook_block().
* @param string $op one of "list", "view", "save" and "configure"
* @param integer $delta code to identify the block
* @param array $edit only for "save" operation
*/
function customsite_block($op = 'list', $delta = 0, $edit = array()) { 

  if ($op == "list") {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();
    $block[0]["info"] = t('Custom Site Functions');
	$block[1]["info"] = t('Hook Implementation');
    return $block;
  } 
   else if ($op == 'view') {
	switch($delta) {
		case 0:
    // Generate our block content

    // Get today's date
    $today = getdate();

    // calculate midnight two months ago
    $start_time = mktime(0, 0, 0,
       $today['mon'], ($today['mday'] - 60), $today['year']);

    // we want items that occur only on the day in question, so  
    // calculate 1 day
    $end_time = time(); // get all posts from one week ago to the present
   
 $limitnum = variable_get("customsite_maxdisp", 3);

  $query = "SELECT nid, title, created FROM " .
           "{node} WHERE created >= %d " .
           "AND created <= %d";

  $query_result = db_query_range($query, $start_time, $end_time, 0, $limitnum);
  
    // content variable that will be returned for display   
  $block_content = ''; 
  while ($links = db_fetch_object($query_result)) {
    $block_content .=  l($links->title, 'node/'. $links->nid) .'<br />';
  }
  
if ($block_content == '') {  
    /* No content.  If we return nothing, the block 
     * doesn't show, which is what we want.
     */
    return;
  }

  // set up the block 
  $block = array();
  
  // add a more link to our page that displays all the links
$options = array( "attributes" => array("title" => t("More events on this day.") ) );
$link = l( t("more"), "customsite", $options );
$block_content .= "<div class=\"more-link\">" . $link . "</div>";

  $block['subject'] = 'Custom Site Function'; 
  $block['content'] = $block_content;
  
	break;
  } //swtich($delta)
  return $block;
  
  }
  
} // function customsite_block
  
  
  
  
  //CONFIGURATION FUNCTION
  
  function customsite_admin() {
  $form = array();

  $form['customsite_maxdisp'] = array(
    '#type' => 'textfield',
    '#title' => t('Maximum number of links'),
    '#default_value' => variable_get('customsite_maxdisp', 3),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t("The maximum number of links to display in the block."),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}  // function customsite_admin

 
  
  //HOOK_MENU
  
  function customsite_menu() {
  
  $items = array();

  $items['admin/settings/customsite'] = array(
    'title' => 'Custom Site Functions module settings',
    'description' => 'Custom Site Functions',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('customsite_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
   );
   
     $items['customsite'] = array(
    'title' => 'Custom Site Functions',
    'page callback' => 'customsite_all',
    'access arguments' => array('access customsite content'),
    'type' => MENU_CALLBACK
  );
  
       $items['lhd'] = array(
    'title' => 'Local Historic District Form',
    'page callback' => 'customsite_lhdpage',
    'access arguments' => array('access customsite content'),
    'type' => MENU_CALLBACK
  );


  return $items;
} // function customsite_menu
 
  
  
  
  //VALIDATION FUNCTION
  
function customsite_admin_validate($form, &$form_state) {
  $maxdisp = $form_state['values']['customsite_maxdisp'];
  if (!is_numeric($maxdisp)) {
    form_set_error('customsite_maxdisp', t('You must enter an integer for the maximum number of links.'));
  }
  else if ($maxdisp <= 0) {
    form_set_error('customsite_maxdisp', t('Maximum number of links must be positive.'));
  }
}


//CUSTOM PAGE CONTENT FUNCTION

function customsite_all() {
  // content variable that will be returned for display
  $page_content = '';

  // Get today's date
  $today = getdate();

  // calculate midnight one week ago
  $start_time = mktime(0, 0, 0, $today['mon'], ($today['mday'] - 60), $today['year']);

  // we want items that occur only on the day in question,
  // so calculate 1 day
  $end_time = time();
  // 60 * 60 * 24 = 86400 seconds in a day

  $query = "SELECT nid, title, created FROM " .
           "{node} WHERE created >= '%d' " .
           " AND created <= '%d'";

  // get the links (no range limit here)
  $queryResult =  db_query($query, $start_time, $end_time);
  while ($links = db_fetch_object($queryResult)) {
    $page_content .= l($links->title, 'node/'.$links->nid) . '<br />';
  }
  // check to see if there was any content before
  // returning the page
  if ($page_content == '') {
    // no content from a week ago, let the user know
    $page_content = "No events occurred on this site on this date in history.";
  }
  return $page_content;
}



//CUSTOM LHD FORM

function customsite_lhdpage() {
return drupal_get_form('customsite_lhdform');
}

function customsite_lhdform($form_state) {

$nid = $_GET['nid'];
$prop_node = node_load($nid);
//drupal_set_message('<pre>' . check_plain(print_r($prop_node, true)) . '</pre>');

//  $nid = $node->nid;
  
//*Major Fieldsets*

$form['top'] = array(
	'#type' => 'fieldset', 
	);

$form['general'] = array(
	'#title' => t('General Information'),
	'#type' => 'fieldset', 
	'#collapsible' => 'TRUE', 
	'#collapsed' => 'TRUE',
	);

$form['arch'] = array(
	'#title' => t('Architectural Features'),
	'#type' => 'fieldset', 
	'#collapsible' => 'TRUE', 
	'#collapsed' => 'TRUE',
	);
	
//*TOP FIELDSET*

//Property Back Reference

  $form['top']['back_ref'] = array(
    '#type' => 'fieldset',
	'#tree' => TRUE,
  );

  $form['top']['back_ref']['0']['nid'] = array(
	'#title' => t('Property Record ID'),
	'#type' => 'textfield',
	'#disabled' => TRUE,
	'#value' => $_GET['nid'],
	'#size' => 4,
	'#tree' => TRUE,
  );
  
//Survey Effort
$field_survey_effort_node=node_load($prop_node->field_survey_effort_ref["0"]["nid"]);


    $form['top']['survey_effort'] = array('#type' => 'fieldset',);
    $form['top']['survey_effort']['field_survey_effort'] = array('#tree' => TRUE,);
	$form['top']['survey_effort']['field_survey_effort_other'] = array('#tree' => TRUE,);
  
  $form['top']['survey_effort']['field_survey_effort']['0']['value'] = array(
    '#type' => 'select',
    '#title' => t('Select Local Historic District Survey Effort'),
    '#default_value' => t($field_survey_effort_node->field_survey_effort["0"]["value"]),
    //'#description' => "",
	'#options' => array(
		'none' => t('select...'),
		'aldridge_place' => t('Aldridge Place'),
		'buddington' => t('Buddington'),
		'grooms' => t('Grooms'),
		'other' => t('Other'),
		),
	'#weight' => 1,
  );
   $form['top']['survey_effort']['field_survey_effort_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Survey Effort'),
    '#default_value' => $field_survey_effort_node->field_other["0"]["value"],
    //'#description' => "",
	'#prefix' => '<div id="edit-value-wrapper"><div id="edit-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-survey-effort-0-value' => array('other')),
	'#weight' => 2,
  );

//Contributing to LHD
$field_contr_lhd_node=node_load($prop_node->field_contr_lhd_ref["0"]["nid"]);

    $form['top']['contr_lhd'] = array('#type' => 'fieldset',);
    $form['top']['contr_lhd']['field_contr_lhd'] = array('#tree' => TRUE,);
	$form['top']['contr_lhd']['field_contr_lhd_justif'] = array('#tree' => TRUE,);
	$form['top']['contr_lhd']['field_contr_lhd_justif_other'] = array('#tree' => TRUE,);
  
  $form['top']['contr_lhd']['field_contr_lhd']['0']['value'] = array(
    '#type' => 'radios',
    '#title' => t('Contributing to Existing or Potential Local Historic District'),
    '#default_value' => t($field_contr_lhd_node->field_contr_lhd["0"]["value"]),
    '#description' => "Selecting 'unknown' will not update the field",
	'#options' => array(
		'yes' => t('Yes'),
		'no' => t('No'),
		'' => t('unknown'),
		),
	'#weight' => -10,
  );
  
  foreach ($field_contr_lhd_node->field_contr_lhd_justif as $val){$field_contr_lhd_justif_flat[] = $val['value'];}; //make flattened array for #default_value
  $form['top']['contr_lhd']['field_contr_lhd_justif']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('If not contributing, what is the justification'),
    '#default_value' => $field_contr_lhd_justif_flat,
    //'#description' => "",
	'#options' => array(
		'integrity' => t('Not Intact/Major Alterations/Low Integrity'),
		'newer' => t('Newer than 50 Years'),
		'other' => t('Other'),
		),
    '#prefix' => '<div id="edit-field-contr-lhd-justif-0-value-wrapper"><div id="edit-field-contr-lhd-justif-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
	'#dependency' => array('radio:field_contr_lhd[0][value]' => array('no')),
	'#weight' => 2,
  );
  
//drupal_set_message('<pre>' . check_plain(print_r($field_contr_lhd_node, true)) . '</pre>');
   $form['top']['contr_lhd']['field_contr_lhd_justif_other']['0']['value'] = array(
    '#type' => 'textarea',
    '#title' => t('Other Justification'),
    '#default_value' => $field_contr_lhd_node->field_other['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-contr-lhd-justif-0-value-other' => array(1)),
	'#weight' => 3,
  );
	
	
	
//*GENERAL FIELDSET*

//TCAD ID
$field_tcad_id_node=node_load($prop_node->field_tcad_id_ref["0"]["nid"]);

 
    $form['general']['tcad_id'] = array('#type' => 'fieldset',);
	$form['general']['tcad_id']['field_is_tcad'] = array('#tree' => TRUE,);
    $form['general']['tcad_id']['field_tcad_id'] = array('#tree' => TRUE,);
    $form['general']['tcad_id']['field_tcad_id_sources'] = array('#tree' => TRUE,);
	
  $form['general']['tcad_id']['field_is_tcad']['0']['value'] = array(
    '#type' => 'checkbox',
    '#title' => t('This property is located on a parcel listed with the Travis Central Assessors District'),
    '#default_value' => $form_state['values']['field_is_tcad']['0']['value'],
    '#description' => "Please visit http://www.traviscad.org/ to determine.",
  );
  
  $form['general']['tcad_id']['field_tcad_id']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Travis Central Assessors District Property ID'),
    '#default_value' => $field_tcad_id_node->field_tcad_id["0"]["value"],
    '#description' => "Six digits",
    '#size' => 6,
    '#maxlength' => 6,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-is-tcad-0-value' => array(1)),
  );
    $form['general']['tcad_id']['field_tcad_id_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#disabled' => TRUE,
    '#value' => 'http://www.traviscad.org/',
    '#description' => "Visit http://www.traviscad.org/ to find Property ID",
    '#size' => 25,
    '#maxlength' => 25,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-is-tcad-0-value' => array(1)),
  );
  
//LEGAL DESCRIPTION , $fieldname = 'geog_lgl_descrp'
$field_geog_lgl_descrp_node=node_load($prop_node->field_geog_lgl_descrp_ref["0"]["nid"]);
  
	$form['general']['geog_lgl_descrp'] = array('#type' => 'fieldset',);
	$form['general']['geog_lgl_descrp']['field_geog_lgl_descrp'] = array('#tree' => TRUE,);
    $form['general']['geog_lgl_descrp']['field_geog_lgl_descrp_sources'] = array('#tree' => TRUE,);
  
  $form['general']['geog_lgl_descrp']['field_geog_lgl_descrp']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Legal Description'),
    '#default_value' => $field_geog_lgl_descrp_node->field_geog_lgl_descrp["0"]["value"],
    //'#description' => "Please enter the Legal Description.",
    '#size' => 60,
    '#maxlength' => 60,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-is-tcad-0-value' => array(1)),
  );
  $form['general']['geog_lgl_descrp']['field_geog_lgl_descrp_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#disabled' => TRUE,
    '#value' => 'http://www.traviscad.org/',
    '#description' => "Visit http://www.traviscad.org/ to find Legal Description",
    '#size' => 25,
    '#maxlength' => 25,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-is-tcad-0-value' => array(1)),
  );
  
//OWNER NAME , $fieldname = 'owner'
$field_owner_node=node_load($prop_node->field_owner_ref["0"]["nid"]);

	$form['general']['owner'] = array('#type' => 'fieldset',);
	$form['general']['owner']['field_owner_name'] = array('#tree' => TRUE,);
	$form['general']['owner']['field_owner_addr'] = array('#tree' => TRUE,);
    $form['general']['owner']['field_owner_sources'] = array('#tree' => TRUE,);
  
  $form['general']['owner']['field_owner_name']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Owner Name'),
    '#default_value' => $field_owner_node->field_owner_name["0"]["value"],
    //'#description' => "Please enter the Owner Name.",
    '#size' => 60,
    '#maxlength' => 60,
  );
    $form['general']['owner']['field_owner_addr']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Owner Address'),
    '#default_value' => $field_owner_node->field_owner_addr["0"]["value"],
    '#description' => "Please enter the owner's full address including city, state and zip code.",
    '#size' => 60,
    '#maxlength' => 60,
  );
  $form['general']['owner']['field_owner_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $field_owner_node->field_sources["0"]["value"],
    //'#description' => "Please enter the source for Owner Name.",
    '#size' => 60,
    '#maxlength' => 60,
  );
  
//AT ORIGNAL LOCATION, $filename = 'at_original_location'
$field_at_original_location_node=node_load($prop_node->field_at_original_location_ref["0"]["nid"]);

	$form['general']['at_original_location'] = array('#type' => 'fieldset',);
	$form['general']['at_original_location']['field_at_original_location'] = array('#tree' => TRUE,);
	$form['general']['at_original_location']['field_original_location_desc'] = array('#tree' => TRUE,);
	$form['general']['at_original_location']['field_date_moved'] = array('#tree' => TRUE,);
    $form['general']['at_original_location']['field_at_original_location_sources'] = array('#tree' => TRUE,);
  
  $form['general']['at_original_location']['field_at_original_location']['0']['value'] = array(
    '#type' => 'radios',
    '#title' => t('Has Property Moved from Original Location'),
    '#default_value' => $field_at_original_location_node->field_at_original_location["0"]["value"],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
		'#options' => array(
		'No' => t('No'),
		'Yes' => t('Yes'),
		),
  );
    $form['general']['at_original_location']['field_original_location_desc']['0']['value'] = array(
    '#type' => 'textarea',
    '#title' => t('Description of Original Location'),
    '#default_value' => $field_at_original_location_node->field_original_location_desc["0"]["value"],
    //'#description' => "",
    '#size' => 60,
    '#maxlength' => 60,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_at_original_location[0][value]' => array('Yes')),
  );
  $form['general']['at_original_location']['field_date_moved']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Date Moved'),
    '#default_value' => $field_at_original_location_node->field_date_moved["0"]["value"],
    '#description' => "Please enter the date in the format MM/DD/YYYY.",
    '#size' => 10,
    '#maxlength' => 10,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_at_original_location[0][value]' => array('Yes')),
  ); 
  $form['general']['at_original_location']['field_at_original_location_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' =>  $field_at_original_location_node->field_sources["0"]["value"],
    //'#description' => "Please enter the source for Owner Name.",
    '#size' => 60,
    '#maxlength' => 60,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_at_original_location[0][value]' => array('Yes')),
  );
  
  
//DATE OF CONSTRUCTION, $filename = 'constr_date'
$field_constr_date_node=node_load($prop_node->field_constr_date_ref["0"]["nid"]);
//drupal_set_message('<pre>' . check_plain(print_r($field_at_original_location_node, true)) . '</pre>');

	$form['general']['constr_date'] = array('#type' => 'fieldset',);
	$form['general']['constr_date']['field_est_act'] = array('#tree' => TRUE,);
	$form['general']['constr_date']['field_constr_date'] = array('#tree' => TRUE,);
	$form['general']['constr_date']['field_construction_early'] = array('#tree' => TRUE,);
	$form['general']['constr_date']['field_construction_late'] = array('#tree' => TRUE,);
	$form['general']['constr_date']['field_constr_date_sources'] = array('#tree' => TRUE,);

  $form['general']['constr_date']['field_est_act']['0']['value'] = array(
    '#type' => 'radios',
    '#title' => t('Date of Construction'),
    '#default_value' => $field_constr_date_node->field_est_act["0"]["value"],
    //'#description' => "",
	'#options' => array(
		'Estimated' => t('Estimated'),
		'Actual' => t('Actual'),
		),
  );
  $form['general']['constr_date']['field_constr_date']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Actual Date of Construction'),
    '#default_value' => $field_constr_date_node->field_constr_date["0"]["value"],
    '#description' => "Please enter the year in the format YYYY.",
    '#size' => 4,
    '#maxlength' => 4,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_est_act[0][value]' => array('Actual')),
  );  
  $form['general']['constr_date']['field_construction_early']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Earliest Estimated Date of Construction'),
    '#default_value' => $field_constr_date_node->field_construction_early["0"]["value"],
    '#description' => "Please enter the year in the format YYYY.",
    '#size' => 4,
    '#maxlength' => 4,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_est_act[0][value]' => array('Estimated')),
  );
  $form['general']['constr_date']['field_construction_late']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Latest Estimated Date of Construction'),
    '#default_value' => $field_constr_date_node->field_construction_late["0"]["value"],
    '#description' => "Please enter the year in the format YYYY.",
    '#size' => 4,
    '#maxlength' => 4,
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('radio:field_est_act[0][value]' => array('Estimated')),
  );
  $form['general']['constr_date']['field_constr_date_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $field_constr_date_node->field_sources["0"]["value"],
    //'#description' => "Please enter the source for Owner Name.",
    '#size' => 60,
    '#maxlength' => 60,
  );

  
	
//*ARCH FEATURES FIELDSET*

//stories, $filename = 'stories'

  $form['arch']['stories'] = array('#type' => 'fieldset',);
  $form['arch']['stories']['field_stories'] = array('#tree' => TRUE,);
  $form['arch']['stories']['field_stories_sources'] = array('#tree' => TRUE,);
  
  $form['arch']['stories']['field_stories']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Stories'),
    '#default_value' => $form_state['values']['field_stories']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  $form['arch']['stories']['field_stories_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_stories_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );


//plan type, $filename = 'plan'

  $form['arch']['plantype'] = array('#title' => 'Plan Type', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['plantype']['field_plantype'] = array('#tree' => TRUE,);
  $form['arch']['plantype']['field_plan_other'] = array('#tree' => TRUE,);
  $form['arch']['plantype']['field_plan_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['plantype']['field_plantype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Plan Type'),
    '#default_value' => $form_state['values']['field_plantype']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'L plan' => t('L plan'),
		'T plan' => t('T plan'),
		'2 room' => t('2 room'),
		'Open' => t('Open'),
		'Modified L-plan' => t('Modified L-plan'),
		'Center passage' => t('Center passage'),
		'Shotgun' => t('Shotgun'),
		'Irregular' => t('Irregular'),
		'Four Square' => t('Four Square'),
		'Rectangular' => t('Rectangular'),
		'other' => t('Other'),
	),
  );
  $form['arch']['plantype']['field_plan_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_plan_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-plantype-0-value-other' => array(1)),
  );
  $form['arch']['plantype']['field_plan_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_plan_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );

//foundationtype, $filename = 'foundation'

  $form['arch']['foundationtype'] = array('#title' => 'Foundation', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['foundationtype']['field_foundationtype'] = array('#tree' => TRUE,);
  $form['arch']['foundationtype']['field_foundation_other'] = array('#tree' => TRUE,);
  $form['arch']['foundationtype']['field_foundation_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['foundationtype']['field_foundationtype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Foundation Type'),
    '#default_value' => $form_state['values']['field_foundationtype']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Pier and beam' => t('Pier and beam'),
		'Stone' => t('Stone'),
		'Brick' => t('Brick'),
		'Slab' => t('Slab'),
		'other' => t('Other'),
	),
  );
  $form['arch']['foundationtype']['field_foundation_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_foundation_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-foundationtype-0-value-other' => array(1)),
  );
  $form['arch']['foundationtype']['field_foundation_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_foundation_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );

  
//wall_facade, $filename = 'wall_facade'

  $form['arch']['wall_facade'] = array('#title' => 'Walls', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['wall_facade']['field_wall_facade'] = array('#tree' => TRUE,);
  $form['arch']['wall_facade']['field_wall_facade_other'] = array('#tree' => TRUE,);
  $form['arch']['wall_facade']['field_wall_facade_sources'] = array('#tree' => TRUE,);
  
  $form['arch']['wall_facade']['field_wall_facade']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Exterior Wall Material'),
    '#default_value' => $form_state['values']['field_wall_facade']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Wood' => t('Wood'),
		'Stucco' => t('Stucco'),
		'Brick' => t('Brick'),
		'Stone' => t('Stone'),
		'Synthetic Siding' => t('Synthetic Siding'),
		'other' => t('Other'),
	),
  );
  $form['arch']['wall_facade']['field_wall_facade_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_wall_facade_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-wall-facade-0-value-other' => array(1)),
  );
  $form['arch']['wall_facade']['field_wall_facade_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_wall_facade_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
 //roofs
   $form['arch']['roof']= array('#title' => 'Roof', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  
//rooftype	$fieldname = 'rooftype'

  $form['arch']['roof']['rooftype'] = array('#type' => 'fieldset',);
  $form['arch']['roof']['rooftype']['field_rooftype'] = array('#tree' => TRUE,);
  $form['arch']['roof']['rooftype']['field_rooftype_other'] = array('#tree' => TRUE,);
  $form['arch']['roof']['rooftype']['field_rooftype_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['roof']['rooftype']['field_rooftype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Roof Shape'),
    '#default_value' => $form_state['values']['field_rooftype']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Gable' => t('Gable'),
		'Hipped' => t('Hipped'),
		'Flat' => t('Flat'),
		'Gambrel' => t('Gambrel'),
		'other' => t('Other'),
	),
  );
  $form['arch']['roof']['rooftype']['field_rooftype_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_rooftype_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-rooftype-0-value-other' => array(1)),
  );
  $form['arch']['roof']['rooftype']['field_rooftype_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_rooftype_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
  
//dormertype, $fieldname = 'dormertype'

  $form['arch']['roof']['dormertype'] = array('#type' => 'fieldset',);
  $form['arch']['roof']['dormertype']['field_dormertype'] = array('#tree' => TRUE,);
  $form['arch']['roof']['dormertype']['field_dormertype_other'] = array('#tree' => TRUE,);
  $form['arch']['roof']['dormertype']['field_dormertype_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['roof']['dormertype']['field_dormertype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Dormer Shape'),
    '#default_value' => $form_state['values']['field_dormertype']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'No Dormers' => t('No Dormers'),
		'Gable' => t('Gable'),
		'Hipped' => t('Hipped'),
		'Flat' => t('Flat'),
		'Gambrel' => t('Gambrel'),
		'other' => t('Other'),
	),
  );
  $form['arch']['roof']['dormertype']['field_dormertype_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_dormertype_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-dormertype-0-value-other' => array(1)),
  );
  $form['arch']['roof']['dormertype']['field_dormertype_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_dormertype_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
//roofmaterials, $fieldname = 'roofmaterials'

  $form['arch']['roof']['roofmaterials'] = array('#type' => 'fieldset',);
  $form['arch']['roof']['roofmaterials']['field_roofmaterials'] = array('#tree' => TRUE,);
  $form['arch']['roof']['roofmaterials']['field_roofmaterials_other'] = array('#tree' => TRUE,);
  $form['arch']['roof']['roofmaterials']['field_roofmaterials_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['roof']['roofmaterials']['field_roofmaterials']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Roof Materials'),
    '#default_value' => $form_state['values']['field_roofmaterials']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Composition Shingles' => t('Composition Shingles'),
		'Tile' => t('Tile'),
		'Metal' => t('Metal'),
		'other' => t('Other'),
	),
  );
  $form['arch']['roof']['roofmaterials']['field_roofmaterials_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_roofmaterials_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-roofmaterials-0-value-other' => array(1)),
  );
  $form['arch']['roof']['roofmaterials']['field_roofmaterials_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_roofmaterials_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
//chim,  $fieldname = 'chimneys'

  $form['arch']['chim'] = array('#title' => 'Chimneys', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['chim']['field_chimneys_int_num'] = array('#tree' => TRUE,);
  $form['arch']['chim']['field_chimneys_ext_num'] = array('#tree' => TRUE,);
  $form['arch']['chim']['field_chimney_material'] = array('#tree' => TRUE,);
  $form['arch']['chim']['field_chimneys_other'] = array('#tree' => TRUE,);
  $form['arch']['chim']['field_chimneys_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['chim']['field_chimneys_int_num']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Interior Chimneys'),
    '#default_value' => $form_state['values']['field_chimneys_int_num']['0']['value'],
    //'#description' => "",
    '#size' => 5,
    '#maxlength' => 5,
  );
  $form['arch']['chim']['field_chimneys_ext_num']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Exterior Chimneys'),
    '#default_value' => $form_state['values']['field_chimneys_ext_num']['0']['value'],
    //'#description' => "",
    '#size' => 5,
    '#maxlength' => 5,
  );
  $form['arch']['chim']['field_chimney_material']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Chimney Materials'),
    '#default_value' => $form_state['values']['field_chimneys_material']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Brick' => t('Brick'),
		'Stone' => t('Stone'),
		'other' => t('Other'),
	),
  );
  $form['arch']['chim']['field_chimneys_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_chimneys_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-chimney-material-0-value-other' => array(1)),
  );
  $form['arch']['chim']['field_chimneys_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_chimneys_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
  //wind, $fieldname = 'windows'

  $form['arch']['wind'] = array('#title' => 'Windows', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['wind']['field_window_type'] = array('#tree' => TRUE,);
  $form['arch']['wind']['field_windows_type_other'] = array('#tree' => TRUE,);
  $form['arch']['wind']['field_windows_material'] = array('#tree' => TRUE,);
  $form['arch']['wind']['field_windows_material_other'] = array('#tree' => TRUE,);
  $form['arch']['wind']['field_windows_screens'] = array('#tree' => TRUE,);
  $form['arch']['wind']['field_windows_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['wind']['field_window_type']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Type of Window'),
    '#default_value' => $form_state['values']['field_window_type']['0']['value'],
    //'#description' => "",
		'#options' => array(
		'Fixed' => t('Fixed'),
		'Casement' => t('Casement'),
		'Single Hung Sash' => t('Single Hung Sash'),
		'Double Hung Sash' => t('Double Hung Sash'),
		'other' => t('Other'),
	),
  );
   $form['arch']['wind']['field_windows_type_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Type'),
    '#default_value' => $form_state['values']['field_windows_type_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-window-type-0-value-other' => array(1)),
  );
  $form['arch']['wind']['field_windows_material']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Material of Window'),
    '#default_value' => $form_state['values']['field_windows_material']['0']['value'],
    //'#description' => "",
		'#options' => array(
		'Wood' => t('Wood'),
		'Steel' => t('Steel'),
		'Aluminum' => t('Aluminum'),
		'Vinyl' => t('Vinyl'),
		'other' => t('Other'),
	),
  );
  $form['arch']['wind']['field_windows_material_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Material'),
    '#default_value' => $form_state['values']['field_windows_material_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-windows-material-0-value-other' => array(1)),
  );
  $form['arch']['wind']['field_windows_screens']['0']['value'] = array(
    '#type' => 'radios',
    '#title' => t('Has Decorative Screens'),
    '#default_value' => $form_state['values']['field_windows_screens']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'Yes' => t('Yes'),
		'No' => t('No'),
	),
  );
    $form['arch']['wind']['field_windows_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_windows_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
   //porches,  $filename = 'porches'

  $form['arch']['porch'] = array('#title' => 'Porches', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['porch']['field_porches'] = array('#tree' => TRUE,);	//yes no
  $form['arch']['porch']['field_porchtype'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porchtype_other'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_roof'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_roof_other'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_post'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_post_material'] = array('#tree' => TRUE,); 	
  $form['arch']['porch']['field_porches_post_other'] = array('#tree' => TRUE,); 	
  $form['arch']['porch']['field_porches_pier_type'] = array('#tree' => TRUE,); 	
  $form['arch']['porch']['field_porches_pier_other'] = array('#tree' => TRUE,); 	
  $form['arch']['porch']['field_porches_rail_material'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_rail_other'] = array('#tree' => TRUE,);
  $form['arch']['porch']['field_porches_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['porch']['field_porches']['0']['value'] = array(
    '#type' => 'radios',
    '#title' => t('Has Porch'),
    '#default_value' => 'No',
    //'#description' => "",
	'#options' => array(
		'No' => t('No'),
		'Yes' => t('Yes'),
	),
  );
  $form['arch']['porch']['field_porchtype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Type of Porch'),
    '#default_value' => $form_state['values']['field_porchtype']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'Full width' => t('Full width'),
		'Partial width' => t('Partial width'),
		'Independent' => t('Independent'),
		'Inset' => t('Inset'),
		'Wraparound' => t('Wraparound'),
		'other' => t('Other'),
	),
	'#prefix' => '<div id="edit-field-porchtype-0-value-wrapper"><div id="edit-field-porchtype-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
	'#dependency' => array('radio:field_porches[0][value]' => array('Yes')),
  );
   $form['arch']['porch']['field_porchtype_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Type'),
    '#default_value' => $form_state['values']['field_porchtype_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-porchtype-0-value-other' => array(1)),
  );
  $form['arch']['porch']['field_porches_roof']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Type of Porch Roof'),
    '#default_value' => $form_state['values']['field_porches_roof']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'None' => t('None'),
		'Gable' => t('Gable'),
		'Shed' => t('Shed'),
		'Hip' => t('Hip'),
		'other' => t('Other'),
	),
	'#prefix' => '<div id="edit-field-porch-roof-0-value-wrapper"><div id="edit-field-porches-roof-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
	'#dependency' => array('radio:field_porches[0][value]' => array('Yes')),
  );
  $form['arch']['porch']['field_porches_roof_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Roof Type'),
    '#default_value' => $form_state['values']['field_porches_roof_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-porches-roof-0-value-other' => array(1)),
  );
  $form['arch']['porch']['field_porches_post']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Porch Posts'),
    '#default_value' => 'none',
    //'#description' => "",
	'#options' => array(
		'None' => t('None'),
		'Full height' => t('Full height'),
		'On piers' => t('On Piers'),
	),
	'#prefix' => '<div id="edit-field-porches-post-0-value-wrapper"><div id="edit-field-porches-post-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
	'#dependency' => array('edit-field-porches-roof-0-value-Gable' => array(1), 'edit-field-porches-roof-0-value-Shed' => array(1), 'edit-field-porches-roof-0-value-Hip' => array(1), 'edit-field-porches-roof-0-value-other' => array(1)),
  );
   $form['arch']['porch']['field_porches_post_material']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Type of Porch Posts'),
    '#default_value' => $form_state['values']['field_porches_post_material']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'Brick' => t('Brick'),
		'Metal' => t('Metal'),
		'Square Wood' => t('Square Wood'),
		'Turned Wood' => t('Turned Wood'),
		'Box Columns' => t('Box Columns'),
		'Classical Columns' => t('Classical Columns'),
		'other' => t('Other'),
	),
    '#prefix' => '<div id="edit-field-porches-post-material-0-value-wrapper"><div id="edit-field-porches-post-material-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
    '#dependency' => array('edit-field-porches-post-0-value-Full-height' => array(1), 'edit-field-porches-post-0-value-On-piers' => array(1)),
  );
   $form['arch']['porch']['field_porches_post_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Porch Post Material'),
    '#default_value' => $form_state['values']['field_porches_post_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-porches-post-material-0-value-other' => array(1)),
  );
    $form['arch']['porch']['field_porches_pier_type']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Type of Porch Piers'),
    '#default_value' => $form_state['values']['field_porches_pier_type']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'Brick' => t('Brick'),
		'Metal' => t('Metal'),
		'Tapered' => t('Tapered'),
		'other' => t('Other'),
	),
    '#prefix' => '<div id="edit-field-porches-pier-type-0-value-wrapper"><div id="edit-field-porches-pier-type-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
    '#dependency' => array('edit-field-porches-post-0-value-On-piers' => array(1)),
  );
   $form['arch']['porch']['field_porches_pier_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Porch Pier Type'),
    '#default_value' => $form_state['values']['field_porches_pier_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-porches-pier-type-0-value-other' => array(1)),
  );
   $form['arch']['porch']['field_porches_rail_material']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Porch Rail Material'),
    '#default_value' => $form_state['values']['field_porches_rail_material']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'None' => t('None'),
		'Metal' => t('Metal'),
		'Square Wood' => t('Square Wood'),
		'Turned Wood' => t('Turned Wood'),
		'other' => t('Other'),
	),
	'#prefix' => '<div id="edit-field-porches-rail-material-0-value-wrapper"><div id="edit-field-porches-rail-material-0-value">',
    '#suffix' => '</div></div>',
	'#process' => array('ctools_dependent_process', 'expand_checkboxes'),
	'#dependency' => array('radio:field_porches[0][value]' => array('Yes')),
  );
  $form['arch']['porch']['field_porches_rail_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Porch Rail Material'),
    '#default_value' => $form_state['values']['field_porches_rail_other']['0']['value'],
    '#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-porches-rail-material-0-value-other' => array(1)),
  );
  
   $form['arch']['porch']['field_porches_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_porches_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
//door features,  $fieldname = 'doors'

  $form['arch']['door'] = array('#title' => 'Doors', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['door']['field_doortype'] = array('#tree' => TRUE,);
  $form['arch']['door']['field_doors_other'] = array('#tree' => TRUE,);
  $form['arch']['door']['field_doors_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['door']['field_doortype']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Door Features'),
    '#default_value' => $form_state['values']['field_doortype']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
	'#options' => array(
		'Single-door primary entrance' => t('Single-door primary entrance'),
		'Double-door primary entrance' => t('Double-door primary entrance'),
		'Glazing' => t('Glazing'),
		'Transom' => t('Transom'),
		'Sidelites' => t('Sidelites'),
		'other' => t('Other'),
	),
  );
  $form['arch']['door']['field_doors_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other'),
    '#default_value' => $form_state['values']['field_doors_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-doortype-0-value-other' => array(1)),
  );
  $form['arch']['door']['field_doors_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_doors_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );
  
//landscape features, $filename = 'landscapefeatures'

  $form['arch']['land'] = array('#title' => 'Landscape Features', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['land']['field_landscapefeatures'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_landscapefeatures_other'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_fence_height'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_fence_material'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_wall_height'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_wall_material'] = array('#tree' => TRUE,);
  $form['arch']['land']['field_landscapefeatures_sources'] = array('#tree' => TRUE,);  
  
  $form['arch']['land']['field_landscapefeatures']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Landscape Features'),
    '#default_value' => $form_state['values']['field_landscapefeatures']['0']['value'],
    //'#description' => "",
		'#options' => array(
		'Sidewalks' => t('Sidewalks'),
		'Terracing' => t('Terracing'),
		'Drives' => t('Drives'),
		'Well' => t('Well'),
		'Gardens' => t('Gardens'),
		'Fence' => t('Fence'),
		'Wall' => t('Wall'),
		'other' => t('Other'),
	),
  );
   $form['arch']['land']['field_landscapefeatures_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Feature'),
    '#default_value' => $form_state['values']['field_landscapefeatures_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-landscapefeatures-0-value-other' => array(1)),
  );
  $form['arch']['land']['field_fence_material']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Fence Material'),
    '#default_value' => $form_state['values']['field_fence_material']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-landscapefeatures-0-value-fence' => array(1)),
  );
  $form['arch']['land']['field_fence_height']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Fence Height'),
    '#default_value' => $form_state['values']['field_fence_height']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-landscapefeatures-0-value-fence' => array(1)),
  );
 $form['arch']['land']['field_wall_material']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Wall Material'),
    '#default_value' => $form_state['values']['field_wall_material']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-landscapefeatures-0-value-wall' => array(1)),
  );
  $form['arch']['land']['field_wall_height']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Wall Height'),
    '#default_value' => $form_state['values']['field_wall_height']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-landscapefeatures-0-value-wall' => array(1)),
  );
  $form['arch']['land']['field_landscapefeatures_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_landscapefeatures_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );



//outbuildings, $fieldname = 'outbuildings'

  $form['arch']['out'] = array('#title' => 'Outbuildings', '#type' => 'fieldset', '#collapsible' => 'TRUE', '#collapsed' => 'TRUE');
  $form['arch']['out']['field_outbuildings'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_garage_single'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_garage_apt'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_garage_wall'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_garage_rooftype'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_garage_roofmaterial'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_barn'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_out_shed'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_outbuildings_other'] = array('#tree' => TRUE,);
  $form['arch']['out']['field_outbuildings_sources'] = array('#tree' => TRUE,);
  
  $form['arch']['out']['field_outbuildings']['0']['value'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Outbuildings'),
    '#default_value' => $form_state['values']['field_outbuildings']['0']['value'],
    //'#description' => "",
	'#options' => array(
		'Single Story Garage' => t('Single Story Garage'),
		'Garage Apartment' => t('Garage Apartment'),
		'Barn' => t('Barn'),
		'Shed' => t('Shed'),
		'other' => t('Other'),
	),
  );
   $form['arch']['out']['field_out_garage_single']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Single Story Garages'),
    '#default_value' => $form_state['values']['field_out_garage_single']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Single-Story-Garage' => array(1)),
	'#size' => 2,
    '#maxlength' => 2,
  );
   $form['arch']['out']['field_out_garage_apt']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Garage Apartments'),
    '#default_value' => $form_state['values']['field_out_garage_apt']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Garage-Apartment' => array(1)),
	'#size' => 2,
    '#maxlength' => 2,
  );
   $form['arch']['out']['field_out_garage_wall']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Garage Wall Material'),
    '#default_value' => $form_state['values']['field_out_garage_wall']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Garage-Apartment' => array(1), 'edit-field-outbuildings-0-value-Single-Story-Garage' => array(1)),
  );
   $form['arch']['out']['field_out_garage_rooftype']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Garage Roof Type'),
    '#default_value' => $form_state['values']['field_out_garage_rooftype']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Garage-Apartment' => array(1), 'edit-field-outbuildings-0-value-Single-Story-Garage' => array(1)),
  );
   $form['arch']['out']['field_out_garage_roofmaterial']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Garage Roof Material'),
    '#default_value' => $form_state['values']['field_out_garage_roofmaterial']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Garage-Apartment' => array(1), 'edit-field-outbuildings-0-value-Single-Story-Garage' => array(1)),
  );
   $form['arch']['out']['field_out_barn']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Barns'),
    '#default_value' => $form_state['values']['field_out_barn']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Barn' => array(1)),
	'#size' => 2,
    '#maxlength' => 2,
  );
   $form['arch']['out']['field_out_shed']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of Sheds'),
    '#default_value' => $form_state['values']['field_out_shed']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-Shed' => array(1)),
	'#size' => 2,
    '#maxlength' => 2,
  );
   $form['arch']['out']['field_outbuildings_other']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Other Outbuildings'),
    '#default_value' => $form_state['values']['field_outbuildings_other']['0']['value'],
    //'#description' => "",
	'#process' => array('ctools_dependent_process'),
	'#dependency' => array('edit-field-outbuildings-0-value-other' => array(1)),
  );
  $form['arch']['out']['field_outbuildings_sources']['0']['value'] = array(
    '#type' => 'textfield',
    '#title' => t('Source'),
    '#default_value' => $form_state['values']['field_outbuildings_sources']['0']['value'],
    //'#description' => "",
    '#size' => 20,
    '#maxlength' => 20,
  );


//BUTTONS

    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
   $form['clear'] = array(
    '#type' => 'submit',
    '#value' => 'Reset form',
    '#validate' => array('customsite_lhdform_clear'),
  );
  return $form;
}


function customsite_lhdform_clear($form, &$form_state) {
  unset ($form_state['values']);  // ensures fields are blank after reset
                                  // button is clicked
  $form_state['rebuild'] = TRUE;
}

function customsite_lhdform_validate($form, &$form_state) {
 /* $tcad_id = $form_state['values']['tcad_id']['0']['value'];
  if (!$tcad_id) {
      form_set_error('tcad_id', 'Please enter a TCAD ID.');
    return;
  }*/
}

function field_node_get($fieldname_ref){

	$property_node = node_load($_GET['nid']);
	$field_nid = $property_node->$fieldname_ref;
	extract($field_nid, EXTR_PREFIX_ALL, "nid");
	extract($nid_0, EXTR_PREFIX_ALL, "field");
	$field_node = node_load($field_nid);

return $field_node;
}


//$fieldname needs to 'tcad_id' or 'geog_lgl_descrp', etc., ie. no 'field' prefix or 'ref' suffix
// make sure that sources fields in form code match $fieldname
function execute_fieldnode($fieldname, $form_state){
	
	$node = field_node_get('field_' . $fieldname . '_ref'); 
	
	$form_state['values']['field_sources']['0']['value'] = $form_state['values']['field_' . $fieldname . '_sources']['0']['value'];
	unset($form_state['values']['field_' . $fieldname . '_sources']);
	
	$form_state['values']['field_other']['0']['value'] = $form_state['values']['field_' . $fieldname . '_other']['0']['value'];
	unset($form_state['values']['field_' . $fieldname . '_other']);
	
	module_load_include('inc', 'node', 'node.pages');
	drupal_execute('fieldnode_' . $fieldname . '_node_form', $form_state, (object) $node);
	
	return $form_state;
}

	//reformat multiple value fields to correct format needed for input
function correct_multi_value_fields($fieldname, $form_state) {
	$form_state['values'][$fieldname]['value'] = $form_state['values'][$fieldname]['0']['value'];
	unset($form_state['values'][$fieldname]['0']);
	
	return $form_state;
}

function customsite_lhdform_submit($form, &$form_state) {

	$multi_value_fields = array('field_plantype','field_foundationtype','field_wall_facade','field_rooftype','field_dormertype','field_roofmaterials','field_chimney_material','field_window_type','field_windows_material','field_porchtype','field_porches_roof','field_porches_post_material','field_porches_pier_type','field_porches_rail_material','field_doortype','field_landscapefeatures','field_outbuildings');
	
	foreach($multi_value_fields as $field){
		$form_state = correct_multi_value_fields($field, $form_state);
	}
	
	drupal_set_message('<pre>' . check_plain(print_r($form_state, true)) . '</pre>');
	//drupal_set_message('<pre>' . check_plain(print_r(field_node_get('field_plan_ref') , true)) . '</pre>');

	$form_state['values']['op'] = t('Save');
	$form_state['values']['revision_moderation'] = 0;
	$orig_form_state = $form_state;
	
	//$form_state = execute_fieldnode('survey_effort', $orig_form_state);
	//$form_state = execute_fieldnode('contr_lhd', $orig_form_state);
	//$form_state = execute_fieldnode('tcad_id', $orig_form_state);
	//$form_state = execute_fieldnode('geog_lgl_descrp', $orig_form_state);
	//$form_state = execute_fieldnode('owner', $orig_form_state);
	//$form_state = execute_fieldnode('at_original_location', $orig_form_state);
	//$form_state = execute_fieldnode('constr_date', $orig_form_state);
	//$form_state = execute_fieldnode('stories', $orig_form_state);
	//$form_state = execute_fieldnode('plan', $orig_form_state);
	//$form_state = execute_fieldnode('foundation', $orig_form_state);
	//$form_state = execute_fieldnode('wall_facade', $orig_form_state);
	//$form_state = execute_fieldnode('rooftype', $orig_form_state);
	//$form_state = execute_fieldnode('dormertype', $orig_form_state);
	//$form_state = execute_fieldnode('roofmaterials', $orig_form_state);
	//$form_state = execute_fieldnode('chimneys', $orig_form_state);
	//$form_state = execute_fieldnode('windows', $orig_form_state);
	//$form_state = execute_fieldnode('porches', $orig_form_state);
	//$form_state = execute_fieldnode('doors', $orig_form_state);
	//$form_state = execute_fieldnode('landscapefeatures', $orig_form_state);
	//$form_state = execute_fieldnode('outbuildings', $orig_form_state);
	
	//drupal_set_message('<pre>' . check_plain(print_r($form_state, true)) . '</pre>');

    $form_state['redirect'] = 'node/' . $_GET['nid']; // Redirects the user.
	
}

