<?php
// $Id: user_help.module

/**
* @file
* Custom functions for this site.
*/

//HOOK_PERM

/**
* Valid permissions for this module
* @return array An array of valid permissions for the user_help module
*/
function user_help_perm() {
  return array('access user_help content');
} // function customsite_perm()


//HOOK_BLOCK
function user_help_block($op = 'list', $delta = 1, $edit = array())  {

global $user;
$block = array();

	if ($op == "list") {
		$block[0]["info"] = t('Help Block');
	}
	
	elseif ($op == 'view') {
		$block[0]['cache'] = BLOCK_NO_CACHE;
		if ( arg(0) == 'map' ) {
			$block['subject'] = 'User Guide';
			$block['content'] = 'This blue block will guide you through the site.  Please browse to a property record using the map below, or click \'Discussion\' above to view the Discussion Forum.';
		}
		// for node/12345 types
		elseif (arg(0) == 'node' && is_numeric(arg(1)) && arg(2) !== 'edit' ) {
			$node = node_load(arg(1));
			if ($node->type == 'property'){
				$block['subject'] = 'User Guide: Property Record';
				if ($user->uid > 0) {//user is logged in
					$block['content'] = 'This is a property record.  As a registered user, you can view, edit, and add new data for this property. <br/>
					<br/>To view, add, or edit individual fields, click their title below and follow the links or switch categories to view other fields.<br/>
					<br/>To attach photographs and documents to this property record, click the \'Edit\' button below.<br/>
					<br/>To fill out all the fields relevant to the Local Historic District Form, click \'Local Historic District Form\' below.';
				}else{//user is anonymous
					$block['content'] = 'This is a property record.  As an unregistered user, you can only view this data and its revision history.  Creating an account will allow you to edit and add new data.<br/>
					<br/>To view individual fields in detail, click their title below or switch categories to view other fields.';
				}
			}elseif($node->type !== 'property' || $node->type !== 'forum'){
				$block['subject'] = 'User Guide: Field Revisions';
				$num_revisions = $node->num_revisions - 1;
				if($num_revisions == 1){$revision='revision';}else{$revision='revisions';}
				if ($user->uid > 0) {//user is logged in
					$block['content'] = 'This is the list of revisions for the property\'s '.$node->title.' field.  This field currently has '.$num_revisions.' '.$revision.'.   The current version is listed first below.  To revise this field, click on the Edit button below.  To return to the property record, click Property Record in the breadcrumb menu below.';
				}else{//user is anonymous
					$block['content'] = 'This is the list of revisions for the property\'s '.$node->title.' field.  This field currently has '.$num_revisions.' '.$revision.'.  The current version is listed first below.  To return to the property record, click Property Record in the breadcrumb menu below.';
				}
			}
		}
		//for edit fields
		elseif(arg(0) == 'node' && is_numeric(arg(1)) && arg(2) == 'edit'){
			$node = node_load(arg(1));
			if ($node->type == 'property'){
				$block['subject'] = 'User Guide: Adding Photos and Documents';
				$block['content'] = 'To add a photo, fill out the fields under the Attached Images group in the red box below, click Upload and then click Save to return to the Property Record.<br/><br/>To add a document (txt, doc, or pdf), fill out the fields under the File Attachments group in the red box below, click Attach and then click Save to turn to the Property Record.';
			}elseif($node->type !== 'property' || $node->type !== 'forum'){
				$block['subject'] = 'User Guide: Editing a Field';
				$block['content'] = 'The edit form for the property\'s '.$node->title.' field is below, with a red border.  Below the form is a list of the previous revisions.  To only view the list of revisions click View below.  To return to the property record, click Property Record in the breadcrumb menu below.<br/><br/>Once you save a new revision, it will enter the moderation queue.  You can view your pending contributions in the My Pending Contributions block to the left.';
			}
			
		}elseif(arg(0) == 'forum'){
			if ($user->uid > 0) {//user is logged in
				$block['subject'] = 'User Guide: Discussion Forum';
				$block['content'] = 'If you run into any problems, or if you have any questions, comments, and suggestions for improvement, please post a new forum topic to discuss these issues with the site administrators and other users.<br/><br/>If you have a comment about a previous posts, click on that topic to access the comment box.';
			}else{//user is anonymous
				$block['subject'] = 'User Guide: Discussion Forum';
				$block['content'] = 'If you run into any problems, or if you have any questions, comments, and suggestions for improvement, please create an account and login to post a new forum topic.';
			}
		}elseif(arg(0) == 'user' && is_numeric(arg(1))){
			global $user;
			$viewed_user = user_load(arg(1));
			if ($user->uid == arg(1)) {
				$block['subject'] = 'User Guide: User Info';
				$block['content'] = 'This is your user information. To view your contributions click Track below.  To edit your information click Edit below.';
			}else{
				$block['subject'] = 'User Guide: User Info';
				$block['content'] = 'This is the user information for <b>'.$viewed_user->name.'</b>.  To view their contributions click Track below.';
			}
		}elseif(arg(0) == 'pending' && $user->uid > 0){
			$block['subject'] = 'User Guide: Your Pending Contributions';
			$block['content'] = 'This is a list of your contributions that are currently in the moderation queue.  These contributions are not publicly visisble yet. ';
		}elseif(arg(0) == 'lhd'&& $user->uid > 0) {
			$block['subject'] = 'User Guide: Local Historic District Form';
			$block['content'] = 'This is the Local Historic District form for the property listed below.  You may fill out as little or as much as you would like;  no field is required.  If there is any existing data for this property, it will show up as the default data below.  Only the data that you add or change will be submitted under your name.';
		}

	}

return $block;
	
}
 