<?php

/**
 * Implementation of hook_install.
 */
function aef_nodeselect_install() {
  //Fully install dependencies, and make them available (D6 flaw)
  set_time_limit(0);
  include_once(drupal_get_path('module', 'aef_utilities') .'/aef_utilities.module');
  aef_utilities_install_dependencies();
}

/**
 * Implementation of hook_uninstall.
 * Delete the variables
 */
function aef_nodeselect_uninstall() {
	variable_del('aef_nodeselect_fields');
	variable_del('aef_number_node');	
}
